{
  "openapi": "3.0.0",
  "info": {
    "version": "1.0.0",
    "title": "API E-commerce Lobtec",
    "description": "Back end, testes e documentação:  NodeJS, MongoDB, Swagger, Insomnia"
  },
  "host": "localhost:45678",
  "basePath": "/",
  "components":{
    "securitySchemes": {
       "bearerAuth": {
          "type": "http",
          "scheme": "bearer",
          "bearerFormat": "JWT"
       }
    }
 },
 "security": [{
  "bearerAuth": []
 }],


  "tags": [
      {
          "name": "Usuário",
          "description": "Usuário endpoints"
      },
      {
      "name": "Categoria",
      "description": "Endpoints de Categoria"
    },
    {
      "name": "Produto",
      "description": "Produto endpoints"
    },
    {
      "name": "Anúncio",
      "description": "Anúncio endpoints"
    },
    
    {
      "name": "Autenticação",
      "description": "Autenticação Endpoint"
    }
  ],
  "schemes": [
    "http",
    "https"
  ],
  "securityDefinitions": {
    "Authorization": {
      "type": "apiKey",
      "name": "Authorization",
      "description": "Value: Bearer ",
      "in": "header",
      "scheme": "bearer"
    }
  },
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/produtos": {
      "get": {
          "tags": [
            "Produto"
          ],
          "description": "Lista todos os produtos cadastrados na base de dados.",
          
          "responses": {
            "201": {
              "description": "Created"
            },
            "401": {
              "description": "Unauthorized"
            },
            "500": {
              "description": "Internal Server Error"
            }
          },
          "security": [
            {
              "Authorization": []
            }
          ]
        }
    },
    "/produto/:id_produto":{
      "get": {
          "tags": [
            "Produto"
          ],
          "description": "Lista os produtos de determinado usuário",
          "parameters": [
            {
              "name": "limit",
              "in": "query",
              "type": "string"
            },
            {
              "name": "page",
              "in": "query",
              "type": "string"
            }
          ],
          "responses": {
            "201": {
              "description": "Created"
            },
            "401": {
              "description": "Unauthorized"
            },
            "500": {
              "description": "Internal Server Error"
            }
          },
          "security": [
            {
              "Authorization": []
            }
          ]
      },
      "post":{
          "tags": [
              "Produto"
          ],
          
          "description": "Cria um produto com os atributos 'nome', 'característica' , 'categoria' e 'subcategoria.'",
          "parameters":[
              {
                  "name": "Nome",
                  "in":"body",
                  "required": true,
                  "schema":{
                      "$ref": "#/models/Produto.js"
                  }
              }
          ],
          "requestBody":{
              "content":{
                  "application/json":{
                      "schema":{
                          "type": "object",
                          "properties":{
                              "nome":{
                                  "type":"string"
                              },
                              "caracteristica":{
                                  "type":"string"
                              },
                              "categoria":{
                                  "type":"string"
                              },
                              "subcategoria":{
                                  "type":"string"                                    
                              }
                          },
                          "example": {
                              "nome": "Samsumg S22",
                              "característica": "Smartphone Samsung S22",
                              "categoria": "Eletrônicos",
                              "Sub-categoria": "Smartphone"
                          }
                      }
                  }
              }
          },
          "responses":{
              "200":{
                  "description": "Produto criado"
              },
              "400": {
                "description": "Bad request"
              },
              "422": {
                "description": "Unprocessable Entity"
              },
              "500": {
                "description": "Internal Server Error"
              }
          }
      },
      "put": {
          "tags": [
            "Produto"
          ],
          "description": "Atualiza os atributos de um determinado produto",
          "requestBody":{
              "content":{
                  "application/json":{
                      "schema":{
                          "type": "string",
                          "example": {
                              "nome": "Samsung Galaxy S22+"
                              
                          }
                      }
                  }
              }
          },
          "parameters": [
            {
              "name": "obj",
              "in": "body",
              "required": true,
              "schema": {
                "$ref": "#/models/Produto.js"
              }
            }
          ],
          "example": {
              "nome": "Samsung S22+"                
          },
          "responses": {
            "200": {
              "description": "Updated"
            },
            "422": {
              "description": "Unprocessable Entity"
            },
            "500": {
              "description": "Internal Server Error"
            }
          },
          "security": [
            {
              "Authorization": []
            }
          ]
        }
    },
   
    "/usuarios": {
      
      "get": {
          "tags": [
            "Usuário"
          ],
          "description": "Lista todos os usuários cadastrados.",
          "parameters": [],
          "responses": {
            "200": {
              "description": "OK"
            },
            "404": {
              "description": "Not Found"
            },
            "500": {
              "description": "Internal Server Error"
            }
          },
          "security": [
            {
              "Authorization": []
            }
          ]
        },
        
        "post":{
          "tags": [
              "Usuário"
          ],
          
          "description": "Cria uma categoria com os atributos 'nome', 'descrição', 'característica' e 'subcategorias(array).'",
          "parameters":[
              {
                  "name": "Nome",
                  "in":"body",
                  "required": true,
                  "schema":{
                      "$ref": "#/models/Usuario.js"
                  }
              }
          ],
          "requestBody":{
              "content":{
                  "application/json":{
                      "schema":{
                          "type": "object",
                          "properties":{
                            "nome":{
                              "type":"string"
                          },
                          "email":{
                              "type":"string"
                          },
                          "cpf":{
                              "type":"string"
                          },
                          "telefone":{
                            "type":"string"
                          },
                          "senha":{
                            "type":"string"
                          },
                          "endereco":{
                              "type":"string",
                              "rua":{
                                  "type":"string"
                              },
                              "number":{
                                  "type":"integer"
                              },
                              "cep":{
                                "type":"string"
                              },
                              "cidade":{
                                "type":"string"
                              },
                              "estado":{
                                "type":"string"
                              }
                          }
                      },
                          "example": {
                            "nome": "Pedro Silva",
                            "email": "pedro@example.com",
                            "data_nascimento": "12/09/2000",
                            "cpf": "22.222.222-22",
                            "telefone": "11 7777-7777",
                            "senha": "1234",
                            "endereco":{                          
                              "rua": "Rua bela flores",
                              "number": "999",
                              "cep":"77777-111",
                              "cidade": "São Paulo",
                              "estado": "SP"
                            }

                          }
                      }
                  }
              }
          },
          "responses":{
              "200":{
                  "description": "Categoria criada"
              },
              "400": {
                "description": "Bad request"
              },
              "422": {
                "description": "Unprocessable Entity"
              },
              "500": {
                "description": "Internal Server Error"
              }
          }
      }
    },
    "/usuario/:usuario_id": {
      "put": {
        "tags": [
          "Usuário"
        ],
        "description": "Atualiza os atributos de um usuário",
        "requestBody":{
            "content":{
                "application/json":{
                    "schema":{
                        "type": "string",
                        "example": {
                            "nome": "Marcelo Silva"
                            
                        }
                    }
                }
            }
        },
        "parameters": [
          {
            "name": "obj",
            "in": "body",
            "required": true
          }
        ],
        "example": {
            "nome": "Marcelo Silva"                
        },
        "responses": {
          "200": {
            "description": "Updated"
          },
          "422": {
            "description": "Unprocessable Entity"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "security": [
          {
            "Authorization": []
          }
        ]
      },
  
      "get": {
        "tags": [
          "Usuário"
        ],
        "description": "",
        "requestBody":{
          "content":{
              "application/json":{
                  "schema":{
                      "type": "string",
                      "example": {
                          "_ID": "62bef50b0d4645ace4d94b2e"
                          
                      }
                  }
              }
          }
      },
        "parameters": [
          {
            "name": "id do usuario",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "404": {
            "description": "Not Found"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },

    "/usuario/:id_usuario/anuncio": {
      "get": {
        "tags": [
          "Usuário"
        ],
        "description": "",
        "requestBody":{
          "content":{
              "application/json":{
                  "schema":{
                      "type": "string",
                      "example": {
                        
                        
                          "_id": "62c09781053569572c72a782",
                          "nome": "Samsung Galaxy S22+",
                          "preco": 25000.56,
                          "autor": "62bf25d5e7baa5ce186786b4",
                          "produto": "62c09554053569572c72a770",
                          "avalizacoes": [],
                          "topico": [
                            {
                              "texto": "Carro mais lixo que ja vi2",
                              "autor": "62c09909f1446a3fe063fdf8",
                              "_id": "62c09db1ff0f094e732432d9",
                              "comentario": []
                            },
                            {
                              "texto": "Esse carro é doido",
                              "autor": "62bf25d5e7baa5ce186786b4",
                              "_id": "62c09dfeff0f094e732432db",
                              "comentario": []
                            },
                            {
                              "texto": "carro lindo",
                              "autor": "62bf25d5e7baa5ce186786b4",
                              "_id": "62c38eec13798e8ac9e5573f",
                              "comentario": []
                            },
                            {
                              "texto": "Esse carro é doido",
                              "autor": "62bf25d5e7baa5ce186786b4",
                              "_id": "62c42c1c224bc6d6e06fdb7d",
                              "comentario": []
                            }
                          ]
                        
                      }
                  }
              }
          }
      },
        "responses": {
          "200": {
            "description": "OK"
          },
          "404": {
            "description": "Not Found"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    
    "/categorios": {
      "get": {
        "tags": [
          "Categoria"
        ],
        "description": "Lista todas as categorias criadas",
        
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Bad request"
          }
        }
      }
      
    },
    "/categorio":{
      "post":{
          "tags": [
              "Categoria"
          ],
          
          "description": "Cria uma categoria com os atributos 'nome', 'descrição', 'característica' e 'subcategorias(array).'",
          "parameters":[
              {
                  "name": "Nome",
                  "in":"body",
                  "required": true
                 
                  
              }
          ],
          "requestBody":{
              "content":{
                  "application/json":{
                      "schema":{
                          "type": "object",
                          "properties":{
                              "nome":{
                                  "type":"string"
                              },
                              "descricao":{
                                  "type":"string"
                              },
                              "caracteristica":{
                                  "type":"string"
                              },
                              "subcategoria":{
                                  "type":"string",
                                  "nome":{
                                      "type":"string"
                                  },
                                  "descricao":{
                                      "type":"string"
                                  }
                              }
                          },
                          "example": {
                              "nome": "Eletronicos",
                              "descrição": "Categoria de produtos Eletronicos",
                              "característica": "Contém eletricidade",
                              "Sub-categorias": ["Smartphone","TV"]
                          }
                      }
                  }
              }
          },
          "responses":{
              "200":{
                  "description": "Categoria criada"
              },
              "400": {
                "description": "Bad request"
              },
              "422": {
                "description": "Unprocessable Entity"
              },
              "500": {
                "description": "Internal Server Error"
              }
          }
      }
    },
    "/categoria/:id_categoria": {
      "put": {
        "tags": [
          "Categoria"
        ],
        "description": "Atualiza informações referentes a uma categoria específica. Pesquisa pelo ID da categoria.",
        "requestBody":{
          "content":{
              "application/json":{
                  "schema":{
                      "type": "string",
                      "example": {
                          "Nome": "Açougue"
                          
                      }
                  }
              }
          }
      },
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "obj",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/models/Categoria.js"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created"
          },
          "401": {
            "description": "Unauthorized"
          },
          "422": {
            "description": "Unprocessable Entity"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "security": [
          {
            "Authorization": []
          }
        ]
      }
      ,
      "get": {
        "tags": [
          "Categoria"
        ],
        "description": "",
        "requestBody":{
          "content":{
              "application/json":{
                  "schema":{
                      "type": "string",
                      "example": {
                          "_ID": "62bef50b0d4645ace4d94b2e"
                          
                      }
                  }
              }
          }
      },
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "404": {
            "description": "Not Found"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      },
      "delete": {
        "tags": [
          "Categoria"
        ],
        "description": "",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "204": {
            "description": "No Content"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "security": [
          {
            "Authorization": []
          }
        ]
      }
    }
  },
  "definitions": {
    "LoginModel": {
      "type": "object",
      "properties": {
        "email": {
          "type": "string",
          "example": "admin@markscodingspot.com"
        },
        "password": {
          "type": "string",
          "example": "Password123#"
        }
      },
      "required": [
        "email",
        "password"
      ]
    },
    "RegisterModel": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "example": "John Snow"
        },
        "email": {
          "type": "string",
          "example": "mail@mail.com"
        },
        "password": {
          "type": "string",
          "example": "Password123#"
        }
      },
      "required": [
        "name",
        "email",
        "password"
      ]
    },
    "UpdateUserModel": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "example": "John Snow"
        }
      },
      "required": [
        "name"
      ]
    },
    "CategoryModel": {
      "type": "object",
      "properties": {
        "nome": {
          "type": "string",
          "example": "Eletrônicos"
        },
        "descricao":{
          "type": "string",
          "example": "Categoria de artigos eletrônicos"
        }
      },
      "required": [
        "title"
      ]
    },
    "StoryModel": {
      "type": "object",
      "properties": {
        "category": {
          "type": "string",
          "example": "6064e654b5c7475bac63ad22"
        },
        "title": {
          "type": "string",
          "example": "Elon Musk Admits He Wants to Travel to Mars Because No One Hates Him There Yet"
        },
        "body": {
          "type": "string",
          "example": "AUSTIN, Texas — Wiping tears from his eyes at a recent press conference, SpaceX CEO Elon Musk revealed that the reason he’s so keen on traveling to Mars is not for the potential benefits to science, but because it’s the one place he can think of where no one hates him yet."
        }
      },
      "required": [
        "category",
        "title",
        "body"
      ]
    },
    "VideoModel": {
      "type": "object",
      "properties": {
        "videoId": {
          "type": "string",
          "example": "QWhJqvuB1ZA"
        },
        "title": {
          "type": "string",
          "example": "Welcome To America with Gad Elmaleh and Ron Livingston"
        }
      },
      "required": [
        "videoId",
        "title"
      ]
    },
    "CommentModel": {
      "type": "object",
      "properties": {
        "story": {
          "type": "string",
          "example": "606576d16bb28e33ecf2872c"
        },
        "body": {
          "type": "string",
          "example": "That's very funny (:"
        }
      },
      "required": [
        "story",
        "body"
      ]
    },
    "VerifyEmailModel": {
      "type": "object",
      "properties": {
        "code": {
          "type": "number",
          "example": 333333
        }
      },
      "required": [
        "code"
      ]
    },
    "ChangePasswordModel": {
      "type": "object",
      "properties": {
        "oldPassword": {
          "type": "string",
          "example": "Password123#"
        },
        "newPassword": {
          "type": "string",
          "example": "Password789#"
        }
      },
      "required": [
        "oldPassword",
        "newPassword"
      ]
    },
    "ForgotPassWordModel": {
      "type": "object",
      "properties": {
        "email": {
          "type": "string",
          "example": "coommark@gmail.com"
        }
      },
      "required": [
        "email"
      ]
    },
    "ResetPasswordModel": {
      "type": "object",
      "properties": {
        "email": {
          "type": "string",
          "example": "coommark@gmail.com"
        },
        "code": {
          "type": "number",
          "example": 999999
        },
        "newPassword": {
          "type": "string",
          "example": "Password789#"
        }
      },
      "required": [
        "email",
        "code",
        "newPassword"
      ]
    }
  }
}